import streamlit as st
import runpy
import os

#link:
# https://github.com/pranjalsh22/cloudy22/blob/main/Poster_2024-11_ISSAC2024_Pranjal_v10-final.pdf

#------------
import base64

def display_clickable_image(image_file, small_width=300):
    # Read and encode image
    with open(image_file, "rb") as f:
        data = f.read()
    encoded = base64.b64encode(data).decode()

    # HTML + CSS + JS for click-to-zoom
    st.markdown(
        f"""
        <style>
        .zoom-img {{
            width: {small_width}px;
            transition: width 0.3s ease;
            cursor: zoom-in;
        }}
        </style>

        <img src="data:image/jpg;base64,{encoded}" 
             class="zoom-img" 
             onclick="this.style.width = this.style.width === '{small_width}px' ? '100%' : '{small_width}px';">
        """,
        unsafe_allow_html=True
    )

# Usage
display_clickable_image("poster.jpg", small_width=300)

#-----------
st.set_page_config(page_title="My Streamlit App", layout="wide")

# Paths to your scripts
PAGES = {
    "Home": {"path": None, "logo": "🏠"},
    "Continuum File": {"path": "pages/save_continuum_file.py", "logo": "💾"},
    "Cloudy Out File": {"path": "pages/cloudy_out_file.py", "logo": "☁️"}
}

if "page" not in st.session_state:
    st.session_state.page = "Home"

cols = st.columns(len(PAGES))
for i, (name, details) in enumerate(PAGES.items()):
    if cols[i].button(f"{details['logo']} {name}"):
        st.session_state.page = name

st.markdown("---")

if st.session_state.page == "Home":
    st.title("CLOUDY output file interpretor")
    st.write("by Pranjal Sharma")
    st.write("The goal of this webapp is analyse the output files generated by Cloudy:the spectral synthesis code.")
    st.header("The .out file")
    st.write("The lines that for the .out file and display visual.")
    st.header("The continuum file")
    st.write("The continuum file generated using the save continuum command can be using to analyse the bolometric luminosity of the cloud or the source.")
    st.header(" My work")
else:
    page_path = PAGES[st.session_state.page]["path"]
    if page_path and os.path.exists(page_path):
        # Execute the page script just like running `streamlit run <file>`
        runpy.run_path(page_path, run_name="__main__")
    else:
        st.error(f"Page not found: {page_path}")
