import streamlit as st
import runpy
import os

#link:
# https://github.com/pranjalsh22/cloudy22/blob/main/Poster_2024-11_ISSAC2024_Pranjal_v10-final.pdf

#------------

import base64

def display_poster_html(image_file, preview_width=400):
    with open(image_file, "rb") as f:
        data = f.read()
    encoded = base64.b64encode(data).decode()
    
    st.markdown(
        f"""
        <div style="text-align:center;">
            <img src="data:image/jpg;base64,{encoded}" 
                 style="max-width:90%; width:{preview_width}px; border:4px solid #ccc; box-shadow:5px 5px 15px rgba(0,0,0,0.3); border-radius:8px;">
        </div>
        """,
        unsafe_allow_html=True
    )

#-----------
st.set_page_config(page_title="My Streamlit App", layout="wide")

# Paths to your scripts
PAGES = {
    "Home": {"path": None, "logo": "🏠"},
    "Continuum File": {"path": "pages/save_continuum_file.py", "logo": "💾"},
    "Cloudy Out File": {"path": "pages/cloudy_out_file.py", "logo": "☁️"}
}

if "page" not in st.session_state:
    st.session_state.page = "Home"

cols = st.columns(len(PAGES))
for i, (name, details) in enumerate(PAGES.items()):
    if cols[i].button(f"{details['logo']} {name}"):
        st.session_state.page = name

st.markdown("---")
#-----------------MAKING HOME PAGE---------------------------
if st.session_state.page == "Home":
    st.title("CLOUDY output file interpretor")
    st.write("by Pranjal Sharma")
    st.write("The goal of this webapp is analyse the output files generated by Cloudy:the spectral synthesis code.")
    st.header("The .out file")
    st.write("The lines that for the .out file and display visual.")
    st.header("The continuum file")
    st.write("The continuum file generated using the save continuum command can be using to analyse the bolometric luminosity of the cloud or the source.")
    st.header(" My work")
    st.title("An Insight into Spectral States in Radio-Loud AGNs")
    col1,col2=st.columns(2)
    with col2:
        st.header("Poster")
        st.link("ISSAC-2024","https://www.astron-soc.in/node/594")
        display_poster_html('poster.jpg',600)
    with col1:
        st.header("Book chapter")
        st.header("Abstract")
        st.write("""
        In this study, we investigate whether **high-excitation radio galaxies (HERGs)** 
        can be interpreted as analogues of the accretion states observed in 
        **stellar-mass black hole X-ray binaries (BHXRBs)**. 
        
        Using a self-developed Python code (**ACCLUM**), we compute the spectrum of a 
        standard accretion disk for a range of black hole masses and accretion parameters. 
        Subsequently, the spectral synthesis code **CLOUDY** was employed to simulate the 
        [O III] λ5007 Å emission from narrow-line region (NLR) clouds photoionized by the 
        disk spectrum. 
        
        The accretion disk was modeled with an **inner truncation at 50 RS** to allow 
        for the presence of an inner advective flow, potentially responsible for jet launching. 
        Our computations demonstrate that such a truncated disk is still capable of 
        producing sufficient ultraviolet luminosity to reproduce the observed [O III] 
        line luminosities in HERGs. 
        
        **Conclusion:**  
        This result supports the interpretation that HERGs may correspond to the 
        **very high/intermediate accretion states (VHS/IS)** of BHXRBs, in which 
        radiatively efficient disks and strong relativistic jets can coexist.
        """)
        
        # Links to the codes
        st.subheader("Related Tools")
        col1, col2 = st.columns(2)
        with col1:
            st.link_button("🔗 ACCLUM (v1)", "https://accretion-disk-spectrum.streamlit.app")
        with col2:
            st.link_button("🔗 ACCLUM 2 (in development)", "https://acclum2.streamlit.app")
        
        # Publication info
        st.subheader("Publication")
        st.write("""
        This work will appear in the forthcoming volume:  
        **“Recent Advances in Astrophysics and Cosmology towards the Mega Telescope Era”**,  
        to be published in the **Astrophysics and Space Science Proceedings** series 
        (Springer Nature).  
        
        This book series is indexed in **Scopus**.  
        """)
        st.link_button("View Series on Springer", "https://link.springer.com/series/7395")

else:
    page_path = PAGES[st.session_state.page]["path"]
    if page_path and os.path.exists(page_path):
        # Execute the page script just like running `streamlit run <file>`
        runpy.run_path(page_path, run_name="__main__")
    else:
        st.error(f"Page not found: {page_path}")
